# Generated by Django 4.2.18 on 2025-02-06 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "0559_team_api_query_rate_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchexportrun",
            name="backfill",
            field=models.ForeignKey(
                help_text="The backfill this run belongs to.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                related_query_name="run",
                to="posthog.batchexportbackfill",
            ),
        ),
    ]
